{
  "openapi": "3.0.0",
  "info": {
    "title": "Microsoft Graph API Example",
    "version": "1.0"
    "x-comment": "Scope: Calendars.Read Calendars.ReadWrite Mail.Read Mail.ReadWrite User.Read Mail.Send"
  },
  "servers": [
    {
      "url": "https://graph.microsoft.com/v1.0"
    }
  ],
  "paths": {
    "/me": {
      "get": {
        "operationId": "getUserProfile",
        "summary": "Get current user profile",
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/me/messages": {
      "get": {
        "operationId": "getUserEmails",
        "summary": "Get user's email messages",
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/me/sendMail": {
      "post": {
        "operationId": "sendUserEmail",
        "summary": "Send an email message",
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "tokenUrl": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": {
              "User.Read": "Read user profile",
              "Mail.Read": "Read user's mail",
              "Mail.ReadWrite": "Read and write access to user's mail",
              "Mail.Send": "Send mail as a user",
              "Calendars.Read": "Read user's calendar",
              "Calendars.ReadWrite": "Read and write access to user's calendar"
            }
          }
        }
      }
    }
  }
}