/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Distance metric for similarity calculation */
export const enum JsDistanceMetric {
  /** Euclidean (L2) distance */
  Euclidean = 'Euclidean',
  /** Cosine similarity (converted to distance) */
  Cosine = 'Cosine',
  /** Dot product (converted to distance for maximization) */
  DotProduct = 'DotProduct',
  /** Manhattan (L1) distance */
  Manhattan = 'Manhattan'
}
/** Quantization configuration */
export interface JsQuantizationConfig {
  /** Quantization type: "none", "scalar", "product", "binary" */
  type: string
  /** Number of subspaces (for product quantization) */
  subspaces?: number
  /** Codebook size (for product quantization) */
  k?: number
}
/** HNSW index configuration */
export interface JsHnswConfig {
  /** Number of connections per layer (M) */
  m?: number
  /** Size of dynamic candidate list during construction */
  efConstruction?: number
  /** Size of dynamic candidate list during search */
  efSearch?: number
  /** Maximum number of elements */
  maxElements?: number
}
/** Database configuration options */
export interface JsDbOptions {
  /** Vector dimensions */
  dimensions: number
  /** Distance metric */
  distanceMetric?: JsDistanceMetric
  /** Storage path */
  storagePath?: string
  /** HNSW configuration */
  hnswConfig?: JsHnswConfig
  /** Quantization configuration */
  quantization?: JsQuantizationConfig
}
/** Vector entry */
export interface JsVectorEntry {
  /** Optional ID (auto-generated if not provided) */
  id?: string
  /** Vector data as Float32Array or array of numbers */
  vector: Float32Array
}
/** Search query parameters */
export interface JsSearchQuery {
  /** Query vector as Float32Array or array of numbers */
  vector: Float32Array
  /** Number of results to return (top-k) */
  k: number
  /** Optional ef_search parameter for HNSW */
  efSearch?: number
}
/** Search result with similarity score */
export interface JsSearchResult {
  /** Vector ID */
  id: string
  /** Distance/similarity score (lower is better for distance metrics) */
  score: number
}
/** Get the version of the Ruvector library */
export declare function version(): string
/** Test function to verify the bindings are working */
export declare function hello(): string
/** Filter for metadata-based search */
export interface JsFilter {
  /** Field name to filter on */
  field: string
  /** Operator: "eq", "ne", "gt", "gte", "lt", "lte", "in", "match" */
  operator: string
  /** Value to compare against (JSON string) */
  value: string
}
/** Collection configuration */
export interface JsCollectionConfig {
  /** Vector dimensions */
  dimensions: number
  /** Distance metric */
  distanceMetric?: JsDistanceMetric
  /** HNSW configuration */
  hnswConfig?: JsHnswConfig
  /** Quantization configuration */
  quantization?: JsQuantizationConfig
}
/** Collection statistics */
export interface JsCollectionStats {
  /** Number of vectors in the collection */
  vectorsCount: number
  /** Disk space used in bytes */
  diskSizeBytes: number
  /** RAM space used in bytes */
  ramSizeBytes: number
}
/** Collection alias */
export interface JsAlias {
  /** Alias name */
  alias: string
  /** Collection name */
  collection: string
}
/** Health response */
export interface JsHealthResponse {
  /** Status: "healthy", "degraded", or "unhealthy" */
  status: string
  /** Version string */
  version: string
  /** Uptime in seconds */
  uptimeSeconds: number
}
/**
 * Get Prometheus metrics
 *
 * # Example
 * ```javascript
 * const metrics = getMetrics();
 * console.log(metrics);
 * ```
 */
export declare function getMetrics(): string
/**
 * Get health status
 *
 * # Example
 * ```javascript
 * const health = getHealth();
 * console.log(`Status: ${health.status}`);
 * console.log(`Uptime: ${health.uptimeSeconds}s`);
 * ```
 */
export declare function getHealth(): JsHealthResponse
export type VectorDB = VectorDb
/** High-performance vector database with HNSW indexing */
export declare class VectorDb {
  /**
   * Create a new vector database with the given options
   *
   * # Example
   * ```javascript
   * const db = new VectorDB({
   *   dimensions: 384,
   *   distanceMetric: 'Cosine',
   *   storagePath: './vectors.db',
   *   hnswConfig: {
   *     m: 32,
   *     efConstruction: 200,
   *     efSearch: 100
   *   }
   * });
   * ```
   */
  constructor(options: JsDbOptions)
  /**
   * Create a vector database with default options
   *
   * # Example
   * ```javascript
   * const db = VectorDB.withDimensions(384);
   * ```
   */
  static withDimensions(dimensions: number): VectorDb
  /**
   * Insert a vector entry into the database
   *
   * Returns the ID of the inserted vector (auto-generated if not provided)
   *
   * # Example
   * ```javascript
   * const id = await db.insert({
   *   vector: new Float32Array([1.0, 2.0, 3.0]),
   *   metadata: { text: 'example' }
   * });
   * ```
   */
  insert(entry: JsVectorEntry): Promise<string>
  /**
   * Insert multiple vectors in a batch
   *
   * Returns an array of IDs for the inserted vectors
   *
   * # Example
   * ```javascript
   * const ids = await db.insertBatch([
   *   { vector: new Float32Array([1, 2, 3]) },
   *   { vector: new Float32Array([4, 5, 6]) }
   * ]);
   * ```
   */
  insertBatch(entries: Array<JsVectorEntry>): Promise<Array<string>>
  /**
   * Search for similar vectors
   *
   * Returns an array of search results sorted by similarity
   *
   * # Example
   * ```javascript
   * const results = await db.search({
   *   vector: new Float32Array([1, 2, 3]),
   *   k: 10,
   *   filter: { category: 'example' }
   * });
   * ```
   */
  search(query: JsSearchQuery): Promise<Array<JsSearchResult>>
  /**
   * Delete a vector by ID
   *
   * Returns true if the vector was deleted, false if not found
   *
   * # Example
   * ```javascript
   * const deleted = await db.delete('vector-id');
   * ```
   */
  delete(id: string): Promise<boolean>
  /**
   * Get a vector by ID
   *
   * Returns the vector entry if found, null otherwise
   *
   * # Example
   * ```javascript
   * const entry = await db.get('vector-id');
   * if (entry) {
   *   console.log('Found:', entry.metadata);
   * }
   * ```
   */
  get(id: string): Promise<JsVectorEntry | null>
  /**
   * Get the number of vectors in the database
   *
   * # Example
   * ```javascript
   * const count = await db.len();
   * console.log(`Database contains ${count} vectors`);
   * ```
   */
  len(): Promise<number>
  /**
   * Check if the database is empty
   *
   * # Example
   * ```javascript
   * if (await db.isEmpty()) {
   *   console.log('Database is empty');
   * }
   * ```
   */
  isEmpty(): Promise<boolean>
}
/** Collection manager for multi-collection support */
export declare class CollectionManager {
  /**
   * Create a new collection manager
   *
   * # Example
   * ```javascript
   * const manager = new CollectionManager('./collections');
   * ```
   */
  constructor(basePath?: string | undefined | null)
  /**
   * Create a new collection
   *
   * # Example
   * ```javascript
   * await manager.createCollection('my_vectors', {
   *   dimensions: 384,
   *   distanceMetric: 'Cosine'
   * });
   * ```
   */
  createCollection(name: string, config: JsCollectionConfig): Promise<void>
  /**
   * List all collections
   *
   * # Example
   * ```javascript
   * const collections = await manager.listCollections();
   * console.log('Collections:', collections);
   * ```
   */
  listCollections(): Promise<Array<string>>
  /**
   * Delete a collection
   *
   * # Example
   * ```javascript
   * await manager.deleteCollection('my_vectors');
   * ```
   */
  deleteCollection(name: string): Promise<void>
  /**
   * Get collection statistics
   *
   * # Example
   * ```javascript
   * const stats = await manager.getStats('my_vectors');
   * console.log(`Vectors: ${stats.vectorsCount}`);
   * ```
   */
  getStats(name: string): Promise<JsCollectionStats>
  /**
   * Create an alias for a collection
   *
   * # Example
   * ```javascript
   * await manager.createAlias('latest', 'my_vectors_v2');
   * ```
   */
  createAlias(alias: string, collection: string): Promise<void>
  /**
   * Delete an alias
   *
   * # Example
   * ```javascript
   * await manager.deleteAlias('latest');
   * ```
   */
  deleteAlias(alias: string): Promise<void>
  /**
   * List all aliases
   *
   * # Example
   * ```javascript
   * const aliases = await manager.listAliases();
   * for (const alias of aliases) {
   *   console.log(`${alias.alias} -> ${alias.collection}`);
   * }
   * ```
   */
  listAliases(): Promise<Array<JsAlias>>
}
