/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Add two decimal strings and return the result as a string */
export declare function addDecimals(a: string, b: string): string
/** Subtract two decimal strings and return the result as a string */
export declare function subtractDecimals(a: string, b: string): string
/** Multiply two decimal strings and return the result as a string */
export declare function multiplyDecimals(a: string, b: string): string
/** Divide two decimal strings and return the result as a string */
export declare function divideDecimals(a: string, b: string): string
/** Calculate gain/loss from a disposal */
export declare function calculateGainLoss(salePrice: string, saleQuantity: string, costBasis: string, costQuantity: string): string
/** Parse an ISO 8601 date string (NAPI export) */
export declare function parseDatetime(dateStr: string): string
/** Format a date string to ISO 8601 (NAPI export) */
export declare function formatDatetime(dateStr: string): string
/** Calculate the number of days between two dates */
export declare function daysBetween(date1: string, date2: string): number
/**
 * Check if a date is within the wash sale period (30 days before or after)
 * US tax law: A wash sale occurs when you sell a security at a loss and
 * purchase the same or substantially identical security within 30 days
 * before or after the sale
 */
export declare function isWithinWashSalePeriod(saleDate: string, purchaseDate: string): boolean
/** Add days to a date */
export declare function addDays(dateStr: string, days: number): string
/** Subtract days from a date */
export declare function subtractDays(dateStr: string, days: number): string
/** Get the start of the tax year for a given date (January 1st) */
export declare function getTaxYearStart(dateStr: string): string
/** Get the end of the tax year for a given date (December 31st) */
export declare function getTaxYearEnd(dateStr: string): string
/** Transaction struct for JavaScript/TypeScript (NAPI export) */
export interface JsTransaction {
  id: string
  transactionType: string
  asset: string
  quantity: string
  price: string
  timestamp: string
  source: string
  fees: string
}
/** Tax lot struct for JavaScript/TypeScript (NAPI export) */
export interface JsTaxLot {
  id: string
  transactionId: string
  asset: string
  quantity: string
  remainingQuantity: string
  costBasis: string
  acquisitionDate: string
}
/** Disposal struct for JavaScript/TypeScript (NAPI export) */
export interface JsDisposal {
  id: string
  saleTransactionId: string
  lotId: string
  asset: string
  quantity: string
  proceeds: string
  costBasis: string
  gainLoss: string
  acquisitionDate: string
  disposalDate: string
  isLongTerm: boolean
}
/** Create a new transaction (NAPI export for testing) */
export declare function createTransaction(tx: JsTransaction): JsTransaction
/** Create a new tax lot (NAPI export for testing) */
export declare function createTaxLot(lot: JsTaxLot): JsTaxLot
/** Create a new disposal (NAPI export for testing) */
export declare function createDisposal(disposal: JsDisposal): JsDisposal
export declare function calculateLifo(sale: JsTransaction, lots: Array<JsTaxLot>): Array<JsDisposal>
export declare function calculateHifo(sale: JsTransaction, lots: Array<JsTaxLot>): Array<JsDisposal>
/** Wash sale detection result for JavaScript/TypeScript */
export interface JsWashSaleResult {
  isWashSale: boolean
  disallowedLoss: string
  replacementTransactionId?: string
  replacementDate?: string
  washWindowStart: string
  washWindowEnd: string
}
/** Adjusted result for JavaScript/TypeScript */
export interface JsAdjustedResult {
  adjustedDisposal: JsDisposal
  adjustedLot: JsTaxLot
  adjustmentAmount: string
}
/**
 * Detect if a disposal triggers a wash sale
 *
 * IRS Rules:
 * 1. Only losses are subject to wash sale (gains are exempt)
 * 2. 61-day window: 30 days before + day of + 30 days after
 * 3. Must be substantially identical securities
 * 4. Replacement purchase must occur in the wash window
 *
 * # Arguments
 * * `disposal` - The disposal to check for wash sale
 * * `all_transactions` - All transactions for this asset
 * * `wash_period_days` - Days before and after (default 30 per IRS)
 *
 * # Returns
 * WashSaleResult with detection details
 */
export declare function detectWashSale(disposal: JsDisposal, allTransactions: Array<JsTransaction>, washPeriodDays?: number | undefined | null): JsWashSaleResult
/**
 * Apply wash sale adjustment to disposal and replacement lot
 *
 * IRS Rules:
 * 1. Disallow the loss on the original disposal (set gain to 0)
 * 2. Add the disallowed loss to the replacement lot's cost basis
 * 3. Extend the holding period to include the original lot's acquisition date
 *
 * # Arguments
 * * `disposal` - The disposal with disallowed loss
 * * `replacement_lot` - The tax lot of the replacement purchase
 * * `disallowed_loss` - The loss amount to adjust (as positive number)
 *
 * # Returns
 * Adjusted disposal and lot
 */
export declare function applyWashSaleAdjustment(disposal: JsDisposal, replacementLot: JsTaxLot, disallowedLoss: string): JsAdjustedResult
/**
 * Detect wash sales for multiple disposals (batch processing)
 *
 * This function efficiently checks multiple disposals against all transactions
 * to identify wash sales. Useful for year-end tax calculations.
 *
 * # Arguments
 * * `disposals` - Array of disposals to check
 * * `transactions` - All transactions across all assets
 *
 * # Returns
 * Array of wash sale results, one per disposal
 */
export declare function detectWashSalesBatch(disposals: Array<JsDisposal>, transactions: Array<JsTransaction>): Array<JsWashSaleResult>
/**
 * Check if a specific purchase is a replacement for a wash sale
 *
 * Helper function to determine if a purchase transaction falls within
 * the wash sale window of a disposal.
 *
 * # Arguments
 * * `disposal_date` - The date of the disposal
 * * `purchase_date` - The date of the purchase
 * * `wash_period_days` - Days before and after (default 30)
 *
 * # Returns
 * True if the purchase is within the wash window
 */
export declare function isWashSaleReplacement(disposalDate: string, purchaseDate: string, washPeriodDays?: number | undefined | null): boolean
/**
 * Calculate the adjusted holding period after wash sale
 *
 * IRS rules require the holding period to include the time the original
 * lot was held before the wash sale.
 *
 * # Arguments
 * * `original_acquisition_date` - When the original lot was acquired
 * * `disposal_date` - When the original lot was disposed
 * * `replacement_acquisition_date` - When the replacement was acquired
 * * `potential_disposal_date` - When considering selling the replacement
 *
 * # Returns
 * Total days held (original period + replacement period)
 */
export declare function calculateWashSaleHoldingPeriod(originalAcquisitionDate: string, disposalDate: string, replacementAcquisitionDate: string, potentialDisposalDate: string): number
/** Get version information */
export declare function getVersion(): string
/** Health check function */
export declare function healthCheck(): boolean
/** NAPI result structure for FIFO disposal calculation */
export interface JsDisposalResult {
  disposals: Array<JsDisposal>
  updatedLots: Array<JsTaxLot>
}
/**
 * Calculate FIFO disposals (NAPI export)
 *
 * # Arguments
 * * `sale` - The sale transaction
 * * `available_lots` - Available tax lots
 *
 * # Returns
 * Result containing disposals and updated lots
 */
export declare function calculateFifo(sale: JsTransaction, availableLots: Array<JsTaxLot>): JsDisposalResult
